on:
  push:
    paths:
      - 'index.xml'
      - '.github/workflows/resource_type.yml'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Gestión de las modificaciones del tipo de recurso: personas físicas
      run:
        echo "Hello, World!"
