on: [push]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - uses: agencia-tributaria/resource_type@main
      with:
        path: ${{ steps.files.outputs.added_modified }}
